# Site settings
title: Simple Primate
description: "Simple Primate is the online home of James Williamson, lynda.com author, speaker and occasional web developer."
baseurl: "" 
url: "http://www.simpleprimate.com" 
tagline: Monkeying around with code

# Build settings
gems: [jekyll-paginate]
highlighter: pygments
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title
